version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/openjdk:11.0.3-jdk-stretch 
orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
