version: 2.1
jobs:
  build:
    machine:
      image: circleci/openjdk:11.0.3-jdk-stretch
      docker_layer_caching: true
orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
